# Generated by Django 5.2.14 on 2026-05-18 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_callback_crm_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='is_called',
            field=models.BooleanField(default=False, verbose_name='Перезвонили (устар.)'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='site_status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_review', 'В работе'), ('kp_sent', 'Коммерческое предложение отправлено'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус на сайте'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Ключ сессии')),
                ('public_number', models.CharField(max_length=32, unique=True, verbose_name='Номер чата')),
                ('visitor_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('page_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Страница')),
                ('status', models.CharField(choices=[('bot', 'Бот'), ('waiting_manager', 'Ожидает менеджера'), ('in_progress', 'В работе'), ('closed', 'Закрыт')], db_index=True, default='bot', max_length=24, verbose_name='Статус')),
                ('manager_note', models.TextField(blank=True, default='', verbose_name='Заметка менеджера')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='Передан менеджеру')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('visitor', 'Клиент'), ('bot', 'Бот'), ('manager', 'Менеджер'), ('system', 'Система')], max_length=16, verbose_name='Отправитель')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at'],
            },
        ),
    ]
