# Generated by Django 5.2.14 on 2026-05-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chat_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='contact_submitted',
            field=models.BooleanField(default=False, verbose_name='Контакты отправлены'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
    ]
