# Generated by Django 5.2.14 on 2026-05-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chat_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='bitrix_lead_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID лида в Битрикс'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='bitrix_stub_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Файл-заглушка CRM'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='bitrix_sync_error',
            field=models.TextField(blank=True, default='', verbose_name='Ошибка CRM'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='bitrix_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в CRM'),
        ),
    ]
